# Generated by Django 4.0.4 on 2022-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0008_createemployeegrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
