# Generated by Django 4.0.4 on 2022-07-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0009_price_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('symbol', models.CharField(max_length=20, null=True)),
                ('formal_name', models.CharField(max_length=50, null=True)),
                ('uqc', models.CharField(max_length=50)),
                ('decimal', models.IntegerField(null=True)),
                ('first_unit', models.CharField(max_length=50)),
                ('conversion', models.CharField(max_length=30)),
                ('second_unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateUnit',
        ),
    ]
