# Generated by Django 4.0.4 on 2022-07-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0012_pancin'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('under_name', models.CharField(max_length=50)),
            ],
        ),
    ]
