# Generated by Django 4.0.4 on 2022-07-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0018_attendance_crt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_crt',
            old_name='unit',
            new_name='units',
        ),
    ]
