# Generated by Django 4.0.4 on 2022-07-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0019_rename_unit_attendance_crt_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_crt',
            name='alias',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_crt',
            name='attendance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_crt',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_crt',
            name='period',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_crt',
            name='under_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance_crt',
            name='units',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
