# Generated by Django 4.0.4 on 2022-07-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0022_salary_crt'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_crt',
            name='calculation_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salary_crt',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salary_crt',
            name='pay_head_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salary_crt',
            name='pay_head_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
