# Generated by Django 4.0.4 on 2022-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0023_salary_crt_calculation_type_salary_crt_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='payroll_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('allias', models.CharField(max_length=100, null=True)),
                ('voucher_type', models.CharField(max_length=100, null=True)),
                ('abbreviation', models.CharField(max_length=100, null=True)),
                ('voucher_numbering_method', models.CharField(max_length=100, null=True)),
                ('effective_dates', models.CharField(max_length=100, null=True)),
                ('zero_val_transactions', models.CharField(max_length=100, null=True)),
                ('optional_voucher', models.CharField(max_length=100, null=True)),
                ('narration_voucher', models.CharField(max_length=100, null=True)),
                ('ledger_narration', models.CharField(max_length=100, null=True)),
                ('print_voucher', models.CharField(max_length=100, null=True)),
                ('classs', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
