# Generated by Django 4.0.4 on 2022-07-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0026_stock_item_crt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item_crt',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
