# Generated by Django 4.0.4 on 2022-07-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0027_stock_item_crt_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_level_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
