# Generated by Django 4.0.4 on 2022-07-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0028_price_level_crt'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item_crt',
            name='per',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock_item_crt',
            name='rate_of_duty',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock_item_crt',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
