# Generated by Django 4.0.4 on 2022-08-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0029_stock_item_crt_per_stock_item_crt_rate_of_duty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='allocate_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate', models.CharField(max_length=100, null=True)),
                ('for_allocate', models.CharField(max_length=100, null=True)),
                ('godown', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('per', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
