# Generated by Django 4.0.4 on 2022-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0030_allocate_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item_crt',
            name='additional',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
