# Generated by Django 4.0.4 on 2022-08-11 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0031_stock_item_crt_additional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_crt',
            name='per',
        ),
    ]
