# Generated by Django 4.0.4 on 2022-08-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0032_remove_salary_crt_per'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll_crt',
            name='ledger_narration',
        ),
        migrations.RemoveField(
            model_name='payroll_crt',
            name='optional_voucher',
        ),
        migrations.RemoveField(
            model_name='payroll_crt',
            name='zero_val_transactions',
        ),
    ]
