# Generated by Django 4.0.4 on 2022-08-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TallyPrimeApp', '0033_remove_payroll_crt_ledger_narration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhead_crt',
            name='attendance_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payhead_crt',
            name='production_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
